# Generated by Django 5.1.4 on 2026-02-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_waba_id_approval_status_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappconfig",
            name="app_id",
            field=models.CharField(
                blank=True,
                help_text="Facebook App ID (required for media uploads during template submission)",
                max_length=100,
            ),
        ),
    ]
