# Generated by Django 5.1.4 on 2026-03-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0008_whatsappconfig_default_pitch"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessage",
            name="meta_error_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="meta_error_message",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
