# Generated by Django 5.1.4 on 2026-03-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0011_rename_greeting_ka"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptemplate",
            name="meta_locale",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Exact locale code Meta registered this template under (populated by Refresh Statuses)",
                max_length=20,
            ),
        ),
    ]
