# Generated by Django 5.1.4 on 2025-12-11 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sales_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='crm.salesteam'),
        ),
    ]
