# Generated by Django 5.1.4 on 2026-01-05 00:58

from django.db import migrations


def add_activities_app(apps, schema_editor):
    """Add Activities app to AppRegistry"""
    AppRegistry = apps.get_model('core', 'AppRegistry')

    AppRegistry.objects.get_or_create(
        name='activities',
        defaults={
            'display_name': 'Activities',
            'description': 'Manage and schedule activities for leads',
            'icon': 'calendar-icon.svg',
            'url_name': 'activities:dashboard',
            'is_active': True,
            'order': 2,  # After CRM
        }
    )


def remove_activities_app(apps, schema_editor):
    """Remove Activities app from AppRegistry"""
    AppRegistry = apps.get_model('core', 'AppRegistry')
    AppRegistry.objects.filter(name='activities').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_sales_team'),
    ]

    operations = [
        migrations.RunPython(add_activities_app, remove_activities_app),
    ]
