# Generated by Django 5.2.8 on 2026-02-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_activities_to_registry"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="extension",
            field=models.CharField(
                blank=True, help_text="SIP extension for VoIP calls", max_length=20
            ),
        ),
    ]
