# Generated by Django 5.1.4 on 2025-12-11 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_id', models.CharField(max_length=100, unique=True, verbose_name='Legal ID')),
                ('legal_name', models.CharField(max_length=200, verbose_name='Legal Name')),
                ('brand_name', models.CharField(blank=True, max_length=200, verbose_name='Brand Name')),
                ('company_phone', models.CharField(blank=True, max_length=20, verbose_name='Company Phone')),
                ('company_mobile', models.CharField(blank=True, max_length=20, verbose_name='Company Mobile')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='Company Email')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industry')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
