# Generated by Django 5.1.4 on 2026-02-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_company_favorite_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("ka", "Georgian")],
                default="en",
                max_length=10,
                verbose_name="Preferred Language",
            ),
        ),
    ]
