# Generated by Django 5.1.4 on 2026-02-01 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SIPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server_ip', models.CharField(help_text='The IP address or hostname of your SIP trunk provider', max_length=255, verbose_name='SIP Server IP/Host')),
                ('server_port', models.PositiveIntegerField(default=5060, help_text='Default is 5060 for UDP', verbose_name='SIP Port')),
                ('username', models.CharField(help_text='Your SIP account username (often your phone number)', max_length=128, verbose_name='SIP Username')),
                ('password', models.CharField(help_text='Your SIP account password', max_length=128, verbose_name='SIP Password')),
                ('caller_id', models.CharField(help_text='The phone number displayed to called parties', max_length=32, verbose_name='Caller ID')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable SIP calling', verbose_name='Active')),
                ('registration_status', models.CharField(choices=[('unknown', 'Unknown'), ('registered', 'Registered'), ('unregistered', 'Unregistered'), ('failed', 'Registration Failed')], default='unknown', max_length=50)),
                ('last_registration_check', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sip_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SIP Settings',
                'verbose_name_plural': 'SIP Settings',
            },
        ),
    ]
