# Generated by Django 5.1.4 on 2026-02-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_settings", "0002_add_sip_settings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SIPSettings",
        ),
    ]
