from .template_views import (
    company_create,
    company_delete,
    company_detail,
    company_edit,
    company_import,
    company_import_confirm,
    company_import_template,
    company_import_upload,
    company_list,
    contact_create,
    contact_delete,
    contact_detail,
    contact_edit,
    toggle_favorite_contact,
)

__all__ = [
    "company_list",
    "company_detail",
    "company_create",
    "company_edit",
    "company_delete",
    "company_import",
    "company_import_upload",
    "company_import_confirm",
    "company_import_template",
    "contact_create",
    "contact_detail",
    "contact_edit",
    "contact_delete",
    "toggle_favorite_contact",
]
