# Generated by Django 5.1.4 on 2025-12-15 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadstage',
            options={'ordering': ['sales_team', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='leadstage',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadstage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadstage',
            name='sales_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_stages', to='crm.salesteam'),
        ),
        migrations.AlterField(
            model_name='leadstage',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='leadstage',
            unique_together={('name', 'sales_team')},
        ),
    ]
