# Generated by Django 5.1.4 on 2025-12-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_team_specific_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='leadstage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
