# Generated by Django 5.1.4 on 2026-01-05 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_add_full_name_to_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-last_activity'], 'verbose_name': 'Opportunity', 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='leadactivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Opportunity Activity', 'verbose_name_plural': 'Opportunity Activities'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Opportunity Title'),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('stage_change', 'Stage Changed'), ('created', 'Opportunity Created'), ('assigned', 'Opportunity Assigned'), ('updated', 'Opportunity Updated')], max_length=20),
        ),
        migrations.CreateModel(
            name='IncomingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(help_text='Initial message or inquiry from the lead')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted to Opportunity'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Sales person assigned to follow up', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incoming_leads', to=settings.AUTH_USER_MODEL)),
                ('converted_opportunity', models.ForeignKey(blank=True, help_text='Opportunity created from this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='crm.lead')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incoming_leads', to=settings.AUTH_USER_MODEL)),
                ('sales_team', models.ForeignKey(blank=True, help_text='Sales team responsible for this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_leads', to='crm.salesteam')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
