# Generated by Django 5.1.4 on 2026-01-05 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_company_favorite_contact'),
        ('crm', '0004_alter_lead_options_alter_leadactivity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incominglead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='incominglead',
            name='name',
        ),
        migrations.RemoveField(
            model_name='incominglead',
            name='phone',
        ),
        migrations.AddField(
            model_name='incominglead',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_leads', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='incominglead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_leads', to='contacts.company'),
        ),
    ]
