# Generated by Django 5.1.4 on 2026-01-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_incominglead_email_remove_incominglead_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
