# Generated by Django 5.1.4 on 2026-02-18 18:28 (modified to add data migration)

import django.db.models.deletion
from django.db import migrations, models


def migrate_incoming_leads(apps, schema_editor):
    """Copy IncomingLead rows to Lead (lead_type=lead) and link converted_from."""
    IL = apps.get_model("crm", "IncomingLead")
    Lead = apps.get_model("crm", "Lead")

    id_map = {}  # IncomingLead.id -> new Lead.id

    for il in IL.objects.select_related("contact", "company").all():
        if il.contact_id:
            try:
                title = il.contact.name or f"Lead #{il.id}"
            except Exception:
                title = f"Lead #{il.id}"
        elif il.company_id:
            try:
                title = il.company.legal_name or f"Lead #{il.id}"
            except Exception:
                title = f"Lead #{il.id}"
        else:
            title = f"Lead #{il.id}"

        new_lead = Lead.objects.create(
            lead_type="lead",
            title=title,
            message=il.message,
            status=il.status,
            company_id=il.company_id,
            contact_id=il.contact_id,
            sales_team_id=il.sales_team_id,
            assigned_to_id=il.assigned_to_id,
            created_by_id=il.created_by_id,
            notes=il.notes,
        )
        Lead.objects.filter(pk=new_lead.pk).update(created_at=il.created_at)
        id_map[il.id] = new_lead.id

    # Set converted_from on existing opportunity records
    for il in IL.objects.filter(converted_opportunity_id__isnull=False):
        new_incoming_id = id_map.get(il.id)
        if new_incoming_id:
            Lead.objects.filter(pk=il.converted_opportunity_id).update(
                converted_from_id=new_incoming_id
            )


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    # atomic=False: prevents PostgreSQL "pending trigger events" error when creating
    # the db_index on lead_type in the same transaction as RunPython inserts.
    atomic = False

    dependencies = [
        ("activities", "0004_unify_lead_incominglead"),
        ("crm", "0006_lead_email_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="converted_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_opportunities",
                to="crm.lead",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_type",
            field=models.CharField(
                choices=[("lead", "Lead"), ("opportunity", "Opportunity")],
                db_index=True,
                default="opportunity",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="message",
            field=models.TextField(blank=True, help_text="Initial inquiry (for incoming leads)"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="crm.leadstage",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("qualified", "Qualified"),
                    ("unqualified", "Unqualified"),
                    ("converted", "Converted"),
                    ("rejected", "Rejected"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_incoming_leads, reverse_migration),
        migrations.DeleteModel(
            name="IncomingLead",
        ),
    ]
