# Generated by Django 5.2.8 on 2026-02-01 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0002_company_favorite_contact"),
        ("crm", "0006_lead_email_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asterisk_channel_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("asterisk_uniqueid", models.CharField(blank=True, max_length=64)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("ringing", "Ringing"),
                            ("answered", "Answered"),
                            ("ended", "Ended"),
                            ("failed", "Failed"),
                            ("busy", "Busy"),
                            ("no_answer", "No Answer"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("from_number", models.CharField(max_length=20)),
                ("to_number", models.CharField(max_length=20)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="contacts.contact",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="crm.lead",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Call",
                "verbose_name_plural": "Calls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=50)),
                ("data", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="calls.call",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Log",
                "verbose_name_plural": "Call Logs",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CallRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="call_recordings/%Y/%m/")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="File size in bytes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording",
                        to="calls.call",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Recording",
                "verbose_name_plural": "Call Recordings",
            },
        ),
    ]
