# Generated by Django 5.1.4 on 2026-02-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0003_encrypt_sip_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="sipsettings",
            name="hold_music",
            field=models.FileField(
                blank=True,
                help_text="Upload a custom hold music file (mp3 or wav)",
                null=True,
                upload_to="hold_music/",
                verbose_name="Custom Hold Music",
            ),
        ),
    ]
