# Generated by Django 5.1.4 on 2026-01-05 00:55

from django.db import migrations


def create_default_activity_types(apps, schema_editor):
    """Create default activity types"""
    ActivityType = apps.get_model('activities', 'ActivityType')

    default_types = [
        {
            'name': 'Phone Call',
            'icon': 'fas fa-phone',
            'color': '#3b82f6',  # Blue
            'is_active': True
        },
        {
            'name': 'Meeting',
            'icon': 'fas fa-calendar',
            'color': '#10b981',  # Green
            'is_active': True
        },
        {
            'name': 'Email',
            'icon': 'fas fa-envelope',
            'color': '#8b5cf6',  # Purple
            'is_active': True
        },
        {
            'name': 'Follow-up',
            'icon': 'fas fa-redo',
            'color': '#f59e0b',  # Orange
            'is_active': True
        },
        {
            'name': 'Note',
            'icon': 'fas fa-sticky-note',
            'color': '#eab308',  # Yellow
            'is_active': True
        },
    ]

    for type_data in default_types:
        ActivityType.objects.get_or_create(
            name=type_data['name'],
            defaults={
                'icon': type_data['icon'],
                'color': type_data['color'],
                'is_active': type_data['is_active']
            }
        )


def reverse_default_activity_types(apps, schema_editor):
    """Remove default activity types"""
    ActivityType = apps.get_model('activities', 'ActivityType')
    default_names = ['Phone Call', 'Meeting', 'Email', 'Follow-up', 'Note']
    ActivityType.objects.filter(name__in=default_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_activity_types, reverse_default_activity_types),
    ]
