# Generated by Django 5.1.4 on 2026-02-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_add_incoming_lead_to_activity"),
        ("crm", "0006_lead_email_optional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="incoming_lead",
        ),
        migrations.AlterField(
            model_name="activity",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_activities",
                to="crm.lead",
                verbose_name="Lead / Opportunity",
            ),
        ),
    ]
