# Re-export template view functions for backward compatibility
from .template_views import (
    api_company_contacts,
    api_company_search,
    api_create_company,
    api_kanban_data,
    api_lead_detail,
    api_lead_list_create,
    api_lead_quick_activity_create,
    api_quick_activity_create,
    api_update_lead_stage,
    crm_dashboard,
    kanban_board,
    lead_convert,
    lead_create,
    lead_delete,
    lead_detail,
    lead_edit,
    lead_list,
    leads_bulk_action,
    opportunity_create,
    opportunity_delete,
    opportunity_edit,
    opportunity_import,
    opportunity_import_confirm,
    opportunity_import_template,
    opportunity_import_upload,
    opportunity_list,
    opportunities_bulk_action,
    send_sales_pitch,
    team_create,
    team_detail,
    team_edit,
    team_list,
    team_stage_create,
    team_stage_delete,
    team_stage_edit,
)

__all__ = [
    "crm_dashboard",
    "kanban_board",
    # Legacy API endpoints
    "api_kanban_data",
    "api_update_lead_stage",
    "api_lead_list_create",
    "api_lead_detail",
    "api_quick_activity_create",
    "api_lead_quick_activity_create",
    "api_create_company",
    "api_company_contacts",
    "api_company_search",
    # Opportunity template views
    "opportunity_list",
    "opportunity_create",
    "opportunity_edit",
    "opportunity_delete",
    "opportunity_import",
    "opportunity_import_upload",
    "opportunity_import_confirm",
    "opportunity_import_template",
    "opportunities_bulk_action",
    "send_sales_pitch",
    # Lead (incoming lead) template views
    "lead_list",
    "lead_create",
    "lead_detail",
    "lead_edit",
    "lead_delete",
    "lead_convert",
    "leads_bulk_action",
    # Team template views
    "team_list",
    "team_detail",
    "team_create",
    "team_edit",
    # Stage template views
    "team_stage_create",
    "team_stage_edit",
    "team_stage_delete",
]
