# Re-export template view functions for backward compatibility
from .template_views import (
    api_company_contacts,
    api_company_search,
    api_create_company,
    api_kanban_data,
    api_lead_detail,
    api_lead_list_create,
    api_lead_quick_activity_create,
    api_quick_activity_create,
    api_update_lead_stage,
    crm_dashboard,
    incoming_lead_convert,
    incoming_lead_create,
    incoming_lead_delete,
    incoming_lead_detail,
    incoming_lead_edit,
    incoming_lead_list,
    kanban_board,
    lead_create,
    lead_delete,
    lead_edit,
    lead_import,
    lead_import_confirm,
    lead_import_template,
    lead_import_upload,
    lead_list,
    team_create,
    team_detail,
    team_edit,
    team_list,
    team_stage_create,
    team_stage_delete,
    team_stage_edit,
)

__all__ = [
    # Dashboard
    "crm_dashboard",
    "kanban_board",
    # Legacy API endpoints (kept for template JS)
    "api_kanban_data",
    "api_update_lead_stage",
    "api_lead_list_create",
    "api_lead_detail",
    "api_quick_activity_create",
    "api_lead_quick_activity_create",
    "api_create_company",
    "api_company_contacts",
    "api_company_search",
    # Lead (Opportunity) template views
    "lead_list",
    "lead_create",
    "lead_edit",
    "lead_delete",
    "lead_import",
    "lead_import_upload",
    "lead_import_confirm",
    "lead_import_template",
    # Team template views
    "team_list",
    "team_detail",
    "team_create",
    "team_edit",
    # Stage template views
    "team_stage_create",
    "team_stage_edit",
    "team_stage_delete",
    # Incoming lead template views
    "incoming_lead_list",
    "incoming_lead_create",
    "incoming_lead_detail",
    "incoming_lead_edit",
    "incoming_lead_delete",
    "incoming_lead_convert",
]
